### ISSUE TITLE
SQL error while migrate/up

### ISSUE THREAD

**Issue by gitrequests** [tuyakhov/yii2-notifications#12]
Error message when yii migrate execute:
create table notification ...Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'

Solved by adding default value to migration:
**@vendor/tuyakhov/yii2-notifications/src/migrations**
```PHP
...
            'created_at' => $this->timestamp()->null(),
...
```
PHP 7.2.10-0ubuntu0.18.04.1 (cli)
MySQL 5.7.23-0ubuntu0.18.04.1 (Ubuntu)

**Comment by tuyakhov** [comment]
Improved in #15
