### ISSUE TITLE
Calling unknown method: yii\db\ActiveQuery::addOnCondition()

### ISSUE THREAD

**Issue by gitrequests** [tuyakhov/yii2-notifications#13]
Yii version: 2.0.14

Error using "database" channel:

> ### Unknown Method – yii\base\UnknownMethodException
> **Calling unknown method: yii\db\ActiveQuery::addOnCondition()**

tuyakhov/yii2-notifications/src/NotifiableTrait.php at line 73 and 78:

```php
    public function getNotifications()
    {
        /** @var $this BaseActiveRecord */
        return $this->hasMany(Notification::className(), ['notifiable_id' => 'id'])
            ->addOnCondition(['notifiable_type' => get_class($this)]);
    }
 
    public function getUnreadNotifications()
    {
        return $this->getNotifications()->addOnCondition(['read_at' => null]);
    }
```

Solved by rename method to "onCondition()". Is it yii2 version specified or not?

**Comment by tuyakhov** [comment]
Fixed in #15
