### ISSUE TITLE
Error of default apiUrl of TelegramChannel

### ISSUE THREAD

**Issue by AntonAcc** [tuyakhov/yii2-notifications#27]
Now it is:

public $apiUrl = "https://api.telegram.org/";

There is a redundant trailing slash which cause an error of API request.

Now, for fixing it, I override it with a config value without a trailing slash.

**Comment by tuyakhov** [comment]
Could you please provide more details and a way to reproduce? What you are talking about shouldn't happen since all the trailing slashes are removed in here [`yii\httpclient\Request::createFullUrl`](https://github.com/yiisoft/yii2-httpclient/blob/master/src/Request.php#L327).

**Comment by AntonAcc** [comment]
Now I can see that it doesn't matter in the last version of yii2-httpclient (2.0.12) to use baseUrl with or without trailing slash. Unfortunately, version 2.0.5 of yii2-httpclient is used in the project in which I meet this error. In that version baseUrl isn't cleaned with trailing slash (https://github.com/yiisoft/yii2-httpclient/blob/2.0.5/Request.php#L306), so there is generated an url https://api.telegram.org//bot<token>/sendMessage (with two slashes in a row) which cause an error.

Furthermore, according to https://tools.ietf.org/html/rfc2616#section-5.1.2, a slash between a host and a path is a part of a path. So, it is a little bit more correct to use baseUrl without a trailing slash. :)

**Comment by tuyakhov** [comment]
I see. Yeah, it makes perfect sense to remove that trailing slash then. Thank you for reporting this.
