### ISSUE TITLE
The MailChannel does not take into consideration the subject field

### ISSUE THREAD

**Issue by mrbig00** [tuyakhov/yii2-notifications#3]
If I specify a subject to a MailMessage, the sent mail does not have a subject, because the subject is not passed to the mailer.

In order to fix this issue, you have to specify the subject at MailChannel.php during compose.
`->setSubject($message->subject)`

https://github.com/tuyakhov/yii2-notifications/blob/2e6ab54cb080f7d91eccae41d8542f6375491551/src/channels/MailChannel.php#L42

**Comment by tuyakhov** [comment]
Thanks @mrbig00
