### ISSUE TITLE
Migration fails. Rename required

### ISSUE THREAD

**Issue by Eseperio** [tuyakhov/yii2-notifications#7]
Migration is not working, and it is because yii migrator is expecting a file with a custom name convention `m000000_000000_XXXXXX`

See [BaseMigrator::903](https://github.com/yiisoft/yii2/blob/9e5c4abdb8d99811b8c4fdc5dc376e22c9f0d662/framework/console/controllers/BaseMigrateController.php#L903)

**Comment by tuyakhov** [comment]
Indeed the database migration has not been tested.
Renamed it in v1.1.2.
Thank you @Eseperio
