### ISSUE TITLE
Wrong class name

### ISSUE THREAD

**Issue by Eseperio** [tuyakhov/yii2-notifications#8]
The default class included is named **Notification**. It fails out of the box.
**THIS IS A PROBLEM OF THE RELEASE 1.1.0**

https://github.com/tuyakhov/yii2-notifications/blob/5fae269a4551884e23ac0999fe64097ab1254cdf/src/channels/ActiveRecordChannel.php#L21

**Comment by tuyakhov** [comment]
Thanks for reporting. Fixed it in 1.1.2.
